site:
  name: VerifiedX
  site: "https://verifiedx.io"
  base: "/"
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: VerifiedX
    template: "%s â€” VerifiedX"
  description: "Tokenized Commerce and Self-Custody for Everyone."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: VerifiedX
    images:
      - url: "~/assets/images/default.jpg"
        width: 1200
        height: 628
    type: website
  twitter:
    handle: "@verifiedx"
    site: "@verifiedx"
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: false
      permalink: "/%slug%" # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: false
      pathname: "blog" # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: false
      pathname: "category" # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: false
      pathname: "tag" # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: "G-YXFKFZLMYT"
      partytown: false

ui:
  theme: "dark:only" # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
